import telebot as t
from telebot import types as ty
import art as a
bot = t.TeleBot('6757281273:AAEvohK2CS2RY2kPTCZbkP5ZQuMmRrXBqAY')
a.tprint('BOT IS ONLINE')
@bot.message_handler(commands=['start', 'main'])
def physic(message):
    cld = ty.InlineKeyboardMarkup(row_width=1)
    b7 = ty.InlineKeyboardButton('7 класс', callback_data='cls:7')
    cld.add(b7)
    bot.send_message(message.chat.id , 'выбирите ваш класс из ниже приведенных:', reply_markup=cld)
@bot.callback_query_handler(func=lambda call:True)
def call(call):
    if call.message:
        if call.data == 'cls:7':
                bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
                cld7 = ty.InlineKeyboardMarkup(row_width=1)
                b71 = ty.InlineKeyboardButton('Запись величин с учетом погрешностей', callback_data='cls:71')
                b72 = ty.InlineKeyboardButton('Формула скорости', callback_data='cls:72')
                b73 = ty.InlineKeyboardButton('Формула пути и времени', callback_data='cls:73')
                b74 = ty.InlineKeyboardButton('Формула плотности', callback_data='cls:74')
                b75 = ty.InlineKeyboardButton('Формула для определения массы тела и объема', callback_data='cls:75')
                b76 = ty.InlineKeyboardButton('Сила тяжести', callback_data='cls:76')
                b77 = ty.InlineKeyboardButton('Вес тела', callback_data='cls:77')
                b78 = ty.InlineKeyboardButton('Закон Гука', callback_data='cls:78')
                b79 = ty.InlineKeyboardButton('Равнодействующая двух сил направленных в одну сторону', callback_data='cls:79')
                b710 = ty.InlineKeyboardButton('Равнодействующая двух сил направленных в разные стороны', callback_data='cls:710')
                b711 = ty.InlineKeyboardButton('Формула для расчета давления', callback_data='cls:711')
                b712 = ty.InlineKeyboardButton('Давление жидкости или газа на дно сосуда', callback_data='cls:712')
                b713 = ty.InlineKeyboardButton('Сила Архимеда', callback_data='cls:713')
                b714 = ty.InlineKeyboardButton('Механическая работа', callback_data='cls:714')
                b715 = ty.InlineKeyboardButton('Мощность', callback_data='cls:715')
                b716 = ty.InlineKeyboardButton('Момент сил', callback_data='cls:716')
                b717 = ty.InlineKeyboardButton('Коофицент полезного действия (КПД)', callback_data='cls:717')
                b718 = ty.InlineKeyboardButton('Потенциальная энергия', callback_data='cls:718')
                b719 = ty.InlineKeyboardButton('Кинетическая энергия', callback_data='cls:719')
                cld7.add(b71 ,b72 ,b73 ,b74 ,b75 ,b76 ,b77 ,b78 ,b79 ,b710,b711,b712,b713,b714,b715,b716,b717,b718,b719)
                bot.send_message(call.message.chat.id , 'выбирите тему из следующих:', reply_markup=cld7)
                bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:71':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Запись величин с учетом погрешностей~\n「A= a ± Δa, где:\n  |~А - измеряемая величина\n  |~a - результат измерений\n  ↳~Δa (читается как: дельта а) - погрешность измерений', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:72':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Формула скорости~\n「v = s/t, где:\n  |~v - скорость (м/c)\n  |~s - путь (в метрах)\n  ↳~t - время (в секундах)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:73':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Формула пути и времени~\n「s = vt, t = s/v, где:\n  |~v - скорость (м/c)\n  |~s - путь (в метрах)\n  ↳~t - время (в секундах)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:74':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Формула плотности~\n「ρ = m/v, где:\n  |~m - масса (в кг)\n  |~ρ (читается как: ро) - плотность масса тела(кг/м^3)\n  ↳~v - объем тела(м^3)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:75':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Формула для определения массы тела и объема~\n「m = ρv, v = m/ρ, где:\n  |~m - масса (в кг)\n  |~ρ (читается как: ро) - плотность масса тела(кг/м^3)\n  ↳~v - объем тела(м^3)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:76':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Сила тяжести~\n「Fтяж. = gm, где:\n  |~m - масса (в кг)\n  ↳~g - ускорение свободного падения(м/с^2)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:77':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Вес тела~\n「P = gm, где:\n  |~m - масса (в кг)\n  ↳~g - ускорение свободного падения(м/с^2)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:78':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id , '~Закон Гука~\n「Fупр. = kΔl, где:\n  |~Fупр. - сила упругости(в Ньютонах)\n  |~k - Жесткость пружины(Н/м)\n  ↳~Δl - l1-l2 удлинение пружины(в метрах)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:79':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Равнодействующая двух сил направленных в одну сторону~\n「R = F1+F2, где:\n  |~R - равнодействующая сила\n  ↳~F1, F2 - силы, действующие на тело(всё в Ньютонах)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:710':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Равнодействующая двух сил направленных в разные стороны~\n「R = F1-F2, где:\n  |~R - равнодействующая сила\n  ↳~F1, F2 - силы, действующие на тело(всё в Ньютонах)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:711':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id , '~Формула для расчета давления~\n「p = F/S, где:\n  |~p - давление (в Паскалях)\n  |~F - сила, действующая перпендикулярно(в Ньютонах)\n  ↳~S - площадь поверхности(м^2)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)#я устал уже...
        elif call.data == 'cls:712':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Давление жидкости или газа на дно сосуда~\n「P = ρgh, где:\n  |~P - давление\n  |~ρ - плотность жидкости\n  |~g - ускорение свободного падения\n  ↳~h - высота столба жидкости', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:713':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Сила Архимеда~\n「F(A) = рgжVт,где:\n  |~р — плотность жидкости (газа)\n  |~g — ускорение свободного падения\n  ↳~V — объём погружённого тела (или часть объёма тела, находящаяся ниже поверхности)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:714':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Механическая работа~\n「A=Fs, где:\n  |~A – работа (в Джоулях)\n  |~F – сила (в Ньютонах)\n  ↳~s – перемещение/путь(в Метрах)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:715':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Мощность~\n「N = a/t, где:\n  |~А - работа (в Джоулях)\n  ↳~t - время (в секундах)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:716':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Момент сил~\n「M = Fl, где:\n  |~F - сила (в Ньютонах)\n  ↳~l - плечо силы (в метрах)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:717':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Коофицент полезного действия (КПД)~\n「η=A/Q, где:\n  |~η — непосредственно КПД\n  |~A — полезная работа\n  ↳~Q — затраченная энергия', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:718':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Потенциальная энергия~\n「Eп= mgh ,где:\n  |~m — масса тела(в метрах)\n  |~g — ускорение свободного падения (м/с^2)\n｜~Еп - потенциальная энергия\n  ↳~h - высота на которое поднято тело (в метрах)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
        elif call.data == 'cls:719':
            bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id, reply_markup=None)
            cld77 = ty.InlineKeyboardMarkup(row_width=1)
            b777= ty.InlineKeyboardButton('Понятно', callback_data='cls:7')
            cld77.add(b777)
            bot.send_message(call.message.chat.id, '~Кинетическая энергия~\n「Ек = mv^2/2, где:\n  |~m — масса объекта(в килограммах)\n  |~v — скорость перемещения объекта в конкретной точке(м/с)\n  ↳~Ек - кинетическая энергия(в Джоулях)', reply_markup=cld77)
            bot.delete_message(call.message.chat.id, call.message.message_id)
bot.infinity_polling()
